TEMPLATE = app
QT = gui core
CONFIG += qt warn_on console debug
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
FORMS = ui/mainwindow.ui
HEADERS = mainwindowimpl.h nodeplotcurve.h dataset.h datasetview.h
SOURCES = mainwindowimpl.cpp main.cpp nodeplotcurve.cpp dataset.cpp datasetview.cpp
INCLUDEPATH = ../qwt-5.0.2/src
LIBS = ../qwt-5.0.2/lib/libqwt.a
TARGET = ../data-mining
