TEMPLATE = app
QT = gui core
CONFIG += qt warn_on release
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
FORMS = ../ui/mainwindow.ui
HEADERS = ../src/mainwindowimpl.h ../src/nodecollection.h ../src/nodeplotcurve.h
SOURCES = ../src/mainwindowimpl.cpp ../src/main.cpp ../src/nodecollection.cpp ../src/nodeplotcurve.cpp
INCLUDEPATH = ../qwt-5.0.2/src
LIBS = ../qwt-5.0.2/lib/libqwt.a
